### ISSUE TITLE
Calib error

### ISSUE THREAD

**Issue by kinggreat24** [chenfeiyi/PBACalib#2]
Thanks for sharing your work. However, I got a bad calib result as shown in the following fig. 
![OptimalT](https://user-images.githubusercontent.com/30688557/229149622-56e59f52-2b6b-425a-9866-6b324dba891e.jpg)

**Comment by chenfeiyi** [comment]
Hi. Can you give more descriptions about what you have done?
For example, 1) the initial parameters you give. 2) How many frames you used to calibrate? 3) What matlab console output?

**Comment by kinggreat24** [comment]
1) the initial parameters:
%% load parameters
% 897.4566,896.7992,635.4040,375.3149
K = [897.4566,0,635.4040;
    0,896.7992,375.3149;
    0,0,1];
D = [-0.4398 0.2329 -0.0011 2.0984e-04 -0.0730];

TInit = [0.0324   -0.9994    0.0130   -0.0152
    0.0215   -0.0123   -0.9997    0.0695
    0.9992    0.0327    0.0211   -0.0132
    0         0         0    1.0000];

2)debug info:
***************load images and pcds*************
load image: /home/kinggreat24/cmake_ws/PBACalib/real/scene2/img/1653901418.578782.jpg
load image: /home/kinggreat24/cmake_ws/PBACalib/real/scene2/img/1653901453.380176.jpg
load image: /home/kinggreat24/cmake_ws/PBACalib/real/scene2/img/1653901505.988883.jpg
load image: /home/kinggreat24/cmake_ws/PBACalib/real/scene2/img/1653901532.748835.jpg
load image: /home/kinggreat24/cmake_ws/PBACalib/real/scene2/img/1653901559.872838.jpg
load image: /home/kinggreat24/cmake_ws/PBACalib/real/scene2/img/1653901600.171732.jpg
load image: /home/kinggreat24/cmake_ws/PBACalib/real/scene2/img/1653901693.395398.jpg
load image: /home/kinggreat24/cmake_ws/PBACalib/real/scene2/img/1653901737.101331.jpg
load image: /home/kinggreat24/cmake_ws/PBACalib/real/scene2/img/1653901852.137347.jpg
load image: /home/kinggreat24/cmake_ws/PBACalib/real/scene2/img/1653901876.169389.jpg
load image: /home/kinggreat24/cmake_ws/PBACalib/real/scene2/img/1653901975.300300.jpg
load image: /home/kinggreat24/cmake_ws/PBACalib/real/scene2/img/1653902011.649615.jpg
load pcd: /home/kinggreat24/cmake_ws/PBACalib/real/scene2/pcd/118.798726.pcd
load pcd: /home/kinggreat24/cmake_ws/PBACalib/real/scene2/pcd/153.598726.pcd
load pcd: /home/kinggreat24/cmake_ws/PBACalib/real/scene2/pcd/206.199046.pcd
load pcd: /home/kinggreat24/cmake_ws/PBACalib/real/scene2/pcd/232.998406.pcd
load pcd: /home/kinggreat24/cmake_ws/PBACalib/real/scene2/pcd/260.099206.pcd
load pcd: /home/kinggreat24/cmake_ws/PBACalib/real/scene2/pcd/300.498886.pcd
load pcd: /home/kinggreat24/cmake_ws/PBACalib/real/scene2/pcd/393.698566.pcd
load pcd: /home/kinggreat24/cmake_ws/PBACalib/real/scene2/pcd/437.398726.pcd
load pcd: /home/kinggreat24/cmake_ws/PBACalib/real/scene2/pcd/552.498886.pcd
load pcd: /home/kinggreat24/cmake_ws/PBACalib/real/scene2/pcd/576.598726.pcd
load pcd: /home/kinggreat24/cmake_ws/PBACalib/real/scene2/pcd/675.798406.pcd
load pcd: /home/kinggreat24/cmake_ws/PBACalib/real/scene2/pcd/712.098886.pcd
***************read sfm model *************
Reading camera 1
Reading image 12
Reading point 1508
***************Camera Pose Optimization*************
-------------f_optm_MLE_cam-------------
iter: 1 x_step: 0.00084728 cost: 19670.5315
iter: 2 x_step: 0.0012121 cost: 19289.7574
iter: 3 x_step: 0.001566 cost: 18841.5074
iter: 4 x_step: 0.0020352 cost: 18418.3248
iter: 5 x_step: 0.0025608 cost: 18032.9186
iter: 6 x_step: 0.0026959 cost: 17616.9874
iter: 7 x_step: 0.0026848 cost: 17170.751
iter: 8 x_step: 0.0033151 cost: 16789.2544
iter: 9 x_step: 0.0041273 cost: 16550.4844
iter: 10 x_step: 0.0047257 cost: 16423.5177
iter: 11 x_step: 0.0049949 cost: 16342.4627
iter: 12 x_step: 0.0047921 cost: 16290.1925
iter: 13 x_step: 0.0042375 cost: 16264.9982
iter: 14 x_step: 0.0034712 cost: 16254.7426
***************Initialize transformation *************
The intial transformation from lidar to camera is:
    0.0293   -0.9995    0.0087   -0.0089
    0.0198   -0.0081   -0.9998    0.0741
    0.9994    0.0294    0.0196   -0.0239
         0         0         0    1.0000

***************optimize transformation *************
data preprocessing...
start calibration
------------f_optm_MLE_with_cam------------
iter: 1 x_step: 0.0009611 cost: 27576.0363
iter: 2 x_step: 0.0012587 cost: 24441.935
iter: 3 x_step: 0.0015237 cost: 22062.9722
iter: 4 x_step: 0.0017812 cost: 20676.6625
iter: 5 x_step: 0.0018962 cost: 19858.2095
iter: 6 x_step: 0.001733 cost: 19326.5292
iter: 7 x_step: 0.0016676 cost: 18965.2045
iter: 8 x_step: 0.0020805 cost: 18676.7503
iter: 9 x_step: 0.0024758 cost: 18430.5832
iter: 10 x_step: 0.0027331 cost: 18246.0205
iter: 11 x_step: 0.0027314 cost: 18124.6244
iter: 12 x_step: 0.0023468 cost: 18055.5321
iter: 13 x_step: 0.0022089 cost: 18022.6791
The final transformation from lidar to camera is:
    0.0276   -0.9996    0.0090   -0.0022
    0.0201   -0.0085   -0.9998    0.0653
    0.9994    0.0278    0.0199   -0.0226
         0         0         0    1.0000

***************Visualize*************
>>

**Comment by kinggreat24** [comment]
> Hi. Can you give more descriptions about what you have done? For example, 1) the initial parameters you give. 2) How many frames you used to calibrate? 3) What matlab console output?

Do you know where the problem is? Can you give me some guidance? Thank you very much.

**Comment by chenfeiyi** [comment]
Sure, please give me several days. I only get a laptop on my hand.  And the computer system is not ready.

**Comment by chenfeiyi** [comment]
I have found the problem. The calibration result is correct. It's something wrong with the data loading and the index of images for visualization. You may need to change the code (already revised in my code):
1. main_cali_real.m: line 27: from "img_folder = fullfile(data_path,'img');" to "img_folder = fullfile(data_path,'img_un');"
2. main_cali_real.m: line 82: from "img_pro = f_pro_livox2cam_i(pc_raw.Location()',imgs_raw{2},K,T3,pc_raw.Intensity');" to "img_pro = f_pro_livox2cam_i(pc_raw.Location()',imgs_raw{1},K,T3,pc_raw.Intensity');"

Sorry for this mistake.

**Comment by kinggreat24** [comment]
> I have found the problem. The calibration result is correct. It's something wrong with the data loading and the index of images for visualization. You may need to change the code (already revised in my code):
> 
> 1. main_cali_real.m: line 27: from "img_folder = fullfile(data_path,'img');" to "img_folder = fullfile(data_path,'img_un');"
> 2. main_cali_real.m: line 82: from "img_pro = f_pro_livox2cam_i(pc_raw.Location()',imgs_raw{2},K,T3,pc_raw.Intensity');" to "img_pro = f_pro_livox2cam_i(pc_raw.Location()',imgs_raw{1},K,T3,pc_raw.Intensity');"
> 
> Sorry for this mistake.

OK, I changed the code and got the right resut. Thank you for your help.

**Comment by chenfeiyi** [comment]
Great! You are welcome
